### ISSUE TITLE
.get_adsorption_sites() fails when called more than once

### ISSUE THREAD

**Issue by mhoffman** [SUNCAT-Center/CatKit#3]
When using the same `catkit.surface.SlabGenerator()` more than once to get adsorption sites (e.g. to get the adsorption sites for more than one termination), it fails with a rather cryptic error message. The problem is demonstrated in this [Gist](https://gist.github.com/9e860ac88d6663c8d3529208461cdc04). From the outside it seems counter-intuitive to instantiate a fresh `SlabGenerator` before every call to this function.

### Steps to reproduce

1. Download the [Gist](https://gist.github.com/9e860ac88d6663c8d3529208461cdc04) in raw format
2. Run the script with the current installation
3. Watch it crash

### What should happen instead

1. Should fail more gracefully
2. Alternatively, if `surface_sites` is very expensive to calculate it should somehow detect if the function has been called with the same `slab` argument or a different one than previously and re-calculate the `surface_atoms`/`surface_sites` iff the `slab` has changed.

**Comment by jboes** [comment]
The slab from the cif file is very unusual in this gif. It doesn't look like it was generated from the Slabgenerator you set up.

**Comment by mhoffman** [comment]
While I can't rule that out, would that make a difference? You can comment in/out the [code block](https://gist.github.com/mhoffman/9e860ac88d6663c8d3529208461cdc04#file-mwe_surface_sites-py-L108) from line 108 and it works just fine. Maybe I am just reading the example wrong?

**Comment by jboes** [comment]
Your Gist should operate as expected now except that the `get_adsorption_sites` function has been changed to `adsorption_sites`

You also have the option to store the slabs surface atoms and use them in the `catkit.adsorption.get_adsorption_sites` function directly now if that is more efficient for the GUI.

``` python
import catkit.adsorption
if __name__ == '__main__':
    mem_file = StringIO.StringIO()
    mem_file.write(bulk_cif)
    mem_file.seek(0)
    bulk_atoms = ase.io.read(mem_file, format='cif')

    in_mem_files = []
    images = []
    for cif_image in slab_cifs:
        mem_file = StringIO.StringIO()
        mem_file.write(cif_image)
        mem_file.seek(0)
        atoms = ase.io.read(mem_file, format='cif')
        images.append(atoms)

    sites_list = []
    for atoms in images:

        sites = catkit.adsorption.get_adsorption_sites(
            atoms,
            surface_sites=[4, 5, 6, 7],
        )
        sites_list.append(sites)

    pprint.pprint(sites_list)
```

Note that no call to the SlabGenerator class is required in this case. The surface sites can be returned at generation time using `gen.get_surface_atoms()`.

**Comment by jboes** [comment]
Hey Max. I'm going to assume this is resolved.
