### ISSUE TITLE
Support of connectivity update when repeating slabs with periodic boundary conditions.

### ISSUE THREAD

**Issue by mhangaard** [SUNCAT-Center/CatKit#65]
When repeating a 1x1 slab composed of a single element, while periodic boundary conditions are True in at least one dimension, a userwarning is thrown, and the connectivity matrix still reflects the 1x1 slab. Ideally the connectivity matrix would be updated for the repeated (e.g. 2x2) slab.

**Comment by mhangaard** [comment]
Workaround for pure metal fcc (111) 2x2 surface: Pass `primitive=False` to the SlabGenerator and avoid the use of `ase.Atoms.repeat`.

**Comment by jboes** [comment]
@mhangaard 

You can also use the size argument to accomplish the effect. See: https://catkit-jboes.readthedocs.io/en/latest/_static/frontmatter/catgen.html#org93a4d12 for an example

And the slab size documentation: https://catkit.readthedocs.io/en/latest/modules/catkit.gen.html#catkit.gen.surface.SlabGenerator.get_slab

**Comment by jboes** [comment]
Having considered this for some time, it seems that on-the-fly graph augmentation will not be possible for all cases since vital symmetries have been lost once the surface is created. The solution is simply to create a slab of the appropriate sizing using the slab generator directly.
